#tomcat
server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB

#配置数据源
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource  # 数据源类型：HiKariCP
    driver-class-name: com.mysql.cj.jdbc.Driver  # mysql驱动
    url: jdbc:mysql://localhost:3306/mytest
    username: root
    password: 123456798
  hikari:
    connection-timeout: 30000 #等待连接池分配连接的最大时长（毫秒）
    minimum-idle: 5
    maximum-pool-size: 20
    auto-commit: true
    idle-timeout: 600000  #连接超时的最大时长（毫秒），超过释放
    pool-name: DateSourceHikariCP
    max-lifetime: 1800000 #连接的生命时长，超时而且没被使用则释放
    connection-test-query: SELECT 1

#mybatis
mybatis:
  type-aliases-apckage: com.boot.pojo  #所有POJO类所在包路径
  mapper-locations: classpath:mapper/*.xml  #mapper映射文件

mapper:
  mappers: com.boot.my.mapper.MyMapper
  not-empty: false
  identity: MYSQL